name: Terraform CI

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=environments/dev init

      - name: Terraform Validate
        run: terraform -chdir=environments/dev validate

      - name: Terraform Plan
        run: terraform -chdir=environments/dev plan
